<?php $this->headTitle($this->translate('Sobre')); ?>
<?php $this->layout()->searchbox = false; ?>



<div class="about" >
    <h1>Sobre </h1>
    <p> <b>O que é Diadorim?</b></p>
    <p>O Diretório de políticas editoriais das revistas científicas brasileiras (Diadorim) é um serviço do <a href="https://ibict.br/" target="_blank">Instituto Brasileiro de Informação em Ciência e Tecnologia (Ibict)</a> que reúne as políticas editoriais sobre o armazenamento e acesso aos artigos das revistas científicas brasileiras em repositórios institucionais de acesso aberto.</p>
    <p><b>Por que o nome Diadorim?</b></p>
    <p>Diadorim é um dos personagens do livro “Grande Sertão: Veredas”, um dos clássicos romances da literatura brasileira cujo autor é João Guimarães Rosa. O nome foi escolhido com vistas a acompanhar a tendência internacional de nomear diretórios e serviços de informação científica homenageando obras da literatura do país em que o sistema foi desenvolvido.</p>
    <p><b>Para que serve o Diadorim?</b></p>
    <p>O Diadorim serve para localizar informações sobre as políticas de acesso e armazenamento dos artigos das revistas científicas brasileiras em repositórios institucionais de acesso aberto. É um serviço voltado para os autores, editores de revistas e para gestores de repositórios institucionais.</p>
    <p><b>Para os autores:</b></p>
    <p>Serve para que os autores saibam se a revista em que pretendem publicar suas pesquisas permite o armazenamento e acesso de uma cópia de seu artigo em repositórios institucionais. Desta forma, os autores podem selecionar uma revista científica que atende suas necessidades.</p>
    <p><b> Para os editores:</b></p>
    <p>Serve para que os editores informem ou estabeleçam a política editorial de suas revistas no que diz respeito ao acesso, armazenamento e condições de uso em repositórios institucionais de acesso aberto. Divulgando a política editorial, a possibilidade de cumprimento do acordo estabelecido entre autores e editores torna-se mais fácil, uma vez que se torna mais conhecido.</p>
    <p><b>Para os gestores dos repositórios institucionais:</b></p>
    <p>Serve para que os gestores dos repositórios institucionais saibam se a instituição editora da revista que publicou determinado artigo permite que ele seja armazenado e acessado no repositórios, bem como as condições estabelecidas para tal.</p>
    <p><b>Por que é importante para o editor cadastrar a política editorial da revista no Diadorim?</b></p>
    <p>Ao cadastrar a política editorial da revista os editores tornam mais visíveis a permissão e as condições para o armazenamento dos artigos em repositórios institucionais. Tornar estas informações mais visíveis auxilia no cumprimento do acordo estabelecido entre os autores e os editores.</p>
    <p><b>Como funciona o sistema de cores?</b></p>
    <p>O sistema de cores funciona para categorizar as políticas editoriais segundo a permissão de armazenamento e acesso dos artigos em repositórios institucionais. Existem quatro categorias para as permissões, são elas:</p>
    <p><b>Amarela:</b></p>
    <p>permite o armazenamento e acesso das versões preprint dos documentos em repositórios institucionais/digitais <span style="color:red;">Tem como colocar a foto do selo na frente de cada definição?</span></p>
    <p><b>Azul:</b></p>
    <p>permite o armazenamento e acesso das versões pós-print dos documentos em repositórios institucionais/digitais</p>
    <p><b>Branca: </b></p>
    <p>apresenta restrições para o armazenamento e acesso das versões preprint e pós-print dos documentos em repositórios institucionais/digitais</p>
    <p><b>Verde:</b></p>
    <p>permite o armazenamento e acesso das versões preprint e pós-print dos documentos em repositórios institucionais/digitais</p>
    <p><b>Qual a diferença do pós-print do autor e do pós-print da revista?</b></p>
    <p>O pós-print do autor corresponde à versão do artigo avaliada pela revista e corrigida pelo autor, mas ainda não publicada pela revista. Já o pós-print da revista refere-se à versão do artigo já corrigida pelo autor e publicada pela revista.</p>
    <p><b>Por que o Diadorim usa este sistema de cores para categorizar as políticas?</b></p>
    <p>Porque este é o sistema mais utilizado internacionalmente para categorizar as políticas editoriais das revistas científicas. O sistema foi criado pelo Diretório Sherpa/Romeo, que é um serviço similar ao Diadorim, mas tem o foco na região europeia. Assim como o Diadorim e o Sherpa/Romeo, existem outros diretórios para as políticas editoriais das revistas científicas, por exemplo: Blimunda, em Portugal, e o Dulcinea, na Espanha.</p>
    <p><b>Como cadastrar minha revista?</b></p>
    <p>O Diadorim funciona de maneira integrada a um outro serviço desenvolvido e mantido pelo <a href="https://miguilim.ibict.br/" target="_blank" rel="noopener noreferrer">Instituto Brasileiro de Informação em Ciência e Tecnologia (Ibict), o Diretório das revistas científicas eletrônicas brasileiras (Miguilim). </a>Desta forma, o cadastro de uma revista deve ser feito diretamente no Miguilim, e assim que o registro for aprovado ele aparecerá automaticamente nos dois serviços.
    </p>
    <p><b>Qualquer revista pode ser cadastrada?</b></p>
    <p>Somente as revistas científicas eletrônicas editadas e publicadas no Brasil podem ser cadastradas. Dentre as revistas científicas brasileiras, qualquer uma pode se cadastrar, independente da área de conhecimento. No entanto, todo cadastro é sujeito à aprovação.</p>
    <p><b>Como alterar as informações do registro?</b></p>
    <p>Para alterar alguma informação do registro da revista, deve ser feita atualização nos dados diretamente no Miguilim. Assim que aprovada, as alterações constarão em ambos os serviços. Em caso de dúvidas, utilize o botão “Contato” do Diadorim para falar com a equipe gestora.
    </p>
</div>