<?php $this->headTitle($this->translate('Sobre')); ?>
<?php $this->layout()->searchbox = false; ?>    

<div class="about">
    <div class="wrapper">
        <!-- imagem gerada separadamente -->
    </div>
    <div class="about-title" id="title-about">
        <h1>Sobre </h1>
        <img class="img-about" src="/diadorim/themes/diadorim/images/diadorim.png" alt="Logo diadorim">
    </div>

    <div class="about-links">
        <ul>
            <li>
                <svg width="24" height="24" viewBox="0 0 24 24" role="img" xmlns="http://www.w3.org/2000/svg" aria-labelledby="linkIconTitle" stroke="#000000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="none" color="#000000">
                    <title id="linkIconTitle">Link</title>
                    <path d="M10.5,15.5 C10.5,14.1666667 10.5,13.5 10.5,13.5 C10.5,10.7385763 8.26142375,8.5 5.5,8.5 C2.73857625,8.5 0.5,10.7385763 0.5,13.5 C0.5,13.5 0.5,14.1666667 0.5,15.5" transform="rotate(-90 5.5 12)" />
                    <path d="M8,12 L16,12" />
                    <path d="M23.5,15.5 C23.5,14.1666667 23.5,13.5 23.5,13.5 C23.5,10.7385763 21.2614237,8.5 18.5,8.5 C15.7385763,8.5 13.5,10.7385763 13.5,13.5 C13.5,13.5 13.5,14.1666667 13.5,15.5" transform="rotate(90 18.5 12)" />
                </svg>
                <a href="#OqDiadorim" rel="noopener noreferrer">O que é Diadorim?</a>
            </li>
            <li>
                <svg width="24" height="24" viewBox="0 0 24 24" role="img" xmlns="http://www.w3.org/2000/svg" aria-labelledby="linkIconTitle" stroke="#000000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="none" color="#000000">
                    <title id="linkIconTitle">Link</title>
                    <path d="M10.5,15.5 C10.5,14.1666667 10.5,13.5 10.5,13.5 C10.5,10.7385763 8.26142375,8.5 5.5,8.5 C2.73857625,8.5 0.5,10.7385763 0.5,13.5 C0.5,13.5 0.5,14.1666667 0.5,15.5" transform="rotate(-90 5.5 12)" />
                    <path d="M8,12 L16,12" />
                    <path d="M23.5,15.5 C23.5,14.1666667 23.5,13.5 23.5,13.5 C23.5,10.7385763 21.2614237,8.5 18.5,8.5 C15.7385763,8.5 13.5,10.7385763 13.5,13.5 C13.5,13.5 13.5,14.1666667 13.5,15.5" transform="rotate(90 18.5 12)" />
                </svg>
                <a href="#Resumo" rel="noopener noreferrer">Resumo da Obra</a>
            </li>

            <li>
                <svg width="24" height="24" viewBox="0 0 24 24" role="img" xmlns="http://www.w3.org/2000/svg" aria-labelledby="linkIconTitle" stroke="#000000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="none" color="#000000">
                    <title id="linkIconTitle">Link</title>
                    <path d="M10.5,15.5 C10.5,14.1666667 10.5,13.5 10.5,13.5 C10.5,10.7385763 8.26142375,8.5 5.5,8.5 C2.73857625,8.5 0.5,10.7385763 0.5,13.5 C0.5,13.5 0.5,14.1666667 0.5,15.5" transform="rotate(-90 5.5 12)" />
                    <path d="M8,12 L16,12" />
                    <path d="M23.5,15.5 C23.5,14.1666667 23.5,13.5 23.5,13.5 C23.5,10.7385763 21.2614237,8.5 18.5,8.5 C15.7385763,8.5 13.5,10.7385763 13.5,13.5 C13.5,13.5 13.5,14.1666667 13.5,15.5" transform="rotate(90 18.5 12)" />
                </svg>
                <a href="#QRDiadorim" rel="noopener noreferrer">Qual a Relação do Diadorim e do Protagonista Riobaldo?</a>
            </li>
            <li>
                <svg width="24" height="24" viewBox="0 0 24 24" role="img" xmlns="http://www.w3.org/2000/svg" aria-labelledby="linkIconTitle" stroke="#000000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="none" color="#000000">
                    <title id="linkIconTitle">Link</title>
                    <path d="M10.5,15.5 C10.5,14.1666667 10.5,13.5 10.5,13.5 C10.5,10.7385763 8.26142375,8.5 5.5,8.5 C2.73857625,8.5 0.5,10.7385763 0.5,13.5 C0.5,13.5 0.5,14.1666667 0.5,15.5" transform="rotate(-90 5.5 12)" />
                    <path d="M8,12 L16,12" />
                    <path d="M23.5,15.5 C23.5,14.1666667 23.5,13.5 23.5,13.5 C23.5,10.7385763 21.2614237,8.5 18.5,8.5 C15.7385763,8.5 13.5,10.7385763 13.5,13.5 C13.5,13.5 13.5,14.1666667 13.5,15.5" transform="rotate(90 18.5 12)" />
                </svg>
                <a href="#PQDiadorim" rel="noopener noreferrer">Por que também o Diadorim se Destaca?</a>
            </li>
        </ul>
    </div>
    <div class="container-about">
        <img class="img-about" id="OqDiadorim" src="/diadorim/themes/diadorim/images/diadorim_ilustracao.png" alt="O que é Diadorim?">
        <p class="text-about">O Diadorim é um personagem icônico da literatura brasileira, presente na obra "Grande Sertão: Veredas", escrita por João Guimarães Rosa. Ele é um jagunço, um guerreiro do sertão, cuja identidade de gênero é motivo de mistério ao longo do livro. Diadorim é retratado como um homem corajoso, habilidoso e leal, que conquista o respeito e a admiração de outros personagens. </p>
        <img class="img-about" id="Resumo" src="/diadorim/themes/diadorim/images/resumo_ilustracao.png" alt="Resumo da obra">
        <p class="text-about">Em resumo, Diadorim é um personagem marcante de "Grande Sertão: Veredas". Sua identidade enigmática, bravura e a relação profunda que desenvolve com Riobaldo fazem dele uma figura inesquecível na literatura brasileira. A obra de Guimarães Rosa nos convida a refletir sobre questões de identidade, gênero e sexualidade, por meio dessa figura complexa e cativante.</p>
        <img class="img-about" id="QRDiadorim" src="/diadorim/themes/diadorim/images/qual_relacao_ilustracao.png" alt="Qual a relação?">
        <p class="text-about">A relação entre Diadorim e o protagonista Riobaldo, que também é narrador da história, é um dos aspectos mais profundos do livro. Riobaldo desenvolve uma forte amizade e admiração por Diadorim, que se transforma em um amor não correspondido. Essa relação intensa e complexa é um fio condutor da narrativa, explorando temas como a descoberta da sexualidade e a luta interna entre os desejos e as convenções sociais.</p>
        <img class="img-about" id="PQDiadorim" src="/diadorim/themes/diadorim/images/porque_diadorim_ilustracao.png" alt="Por que o Diadorim?">
        <p class="text-about">Além de sua identidade enigmática, Diadorim também se destaca por sua bravura e habilidades como guerreiro. Ele é um líder nato, respeitado por seu conhecimento do sertão e por sua destreza em batalha. Diadorim é um dos personagens mais fortes e corajosos do livro, enfrentando perigos e desafios com determinação e valentia.</p>
    </div>
    <div class="topo">
        <a href="#title-about" rel="noopener noreferrer" class="btn-topo">
            <svg fill="#ff7900" width="24" height="24" viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg">
                <path d="M 16 6.59375 L 15.28125 7.28125 L 2.78125 19.78125 L 4.21875 21.21875 L 16 9.4375 L 27.78125 21.21875 L 29.21875 19.78125 L 16.71875 7.28125 Z" />
            </svg>
        </a>
        <span class="text-about">Topo</span>
    </div>
</div>