<?php $this->headTitle($this->translate('Sobre')); ?>
<?php $this->layout()->searchbox = false; ?>

<div class="about">
    <div class="wrapper">
        <!-- imagem gerada separadamente -->
    </div>
    <!-- <div class="about-title" id="title-about">
        <img class="img-about" src="../images/diadorim-about.png" alt="Logo diadorim">
    </div> -->
    <div class="about-links">
        <ul>
            <li>
                <svg width="24" height="24" viewBox="0 0 24 24" role="img" xmlns="http://www.w3.org/2000/svg" aria-labelledby="linkIconTitle" stroke="#000000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="none" color="#000000">
                    <title id="linkIconTitle">Link</title>
                    <path d="M10.5,15.5 C10.5,14.1666667 10.5,13.5 10.5,13.5 C10.5,10.7385763 8.26142375,8.5 5.5,8.5 C2.73857625,8.5 0.5,10.7385763 0.5,13.5 C0.5,13.5 0.5,14.1666667 0.5,15.5" transform="rotate(-90 5.5 12)" />
                    <path d="M8,12 L16,12" />
                    <path d="M23.5,15.5 C23.5,14.1666667 23.5,13.5 23.5,13.5 C23.5,10.7385763 21.2614237,8.5 18.5,8.5 C15.7385763,8.5 13.5,10.7385763 13.5,13.5 C13.5,13.5 13.5,14.1666667 13.5,15.5" transform="rotate(90 18.5 12)" />
                </svg>
                <a href="#OqDiadorim" rel="noopener noreferrer">O que é Diadorim?</a>
            </li>
            <li>
                <svg width="24" height="24" viewBox="0 0 24 24" role="img" xmlns="http://www.w3.org/2000/svg" aria-labelledby="linkIconTitle" stroke="#000000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="none" color="#000000">
                    <title id="linkIconTitle">Link</title>
                    <path d="M10.5,15.5 C10.5,14.1666667 10.5,13.5 10.5,13.5 C10.5,10.7385763 8.26142375,8.5 5.5,8.5 C2.73857625,8.5 0.5,10.7385763 0.5,13.5 C0.5,13.5 0.5,14.1666667 0.5,15.5" transform="rotate(-90 5.5 12)" />
                    <path d="M8,12 L16,12" />
                    <path d="M23.5,15.5 C23.5,14.1666667 23.5,13.5 23.5,13.5 C23.5,10.7385763 21.2614237,8.5 18.5,8.5 C15.7385763,8.5 13.5,10.7385763 13.5,13.5 C13.5,13.5 13.5,14.1666667 13.5,15.5" transform="rotate(90 18.5 12)" />
                </svg>
                <a href="#nameDiadorim" rel="noopener noreferrer">Por que o nome Diadorim?</a>
            </li>

            <li>
                <svg width="24" height="24" viewBox="0 0 24 24" role="img" xmlns="http://www.w3.org/2000/svg" aria-labelledby="linkIconTitle" stroke="#000000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="none" color="#000000">
                    <title id="linkIconTitle">Link</title>
                    <path d="M10.5,15.5 C10.5,14.1666667 10.5,13.5 10.5,13.5 C10.5,10.7385763 8.26142375,8.5 5.5,8.5 C2.73857625,8.5 0.5,10.7385763 0.5,13.5 C0.5,13.5 0.5,14.1666667 0.5,15.5" transform="rotate(-90 5.5 12)" />
                    <path d="M8,12 L16,12" />
                    <path d="M23.5,15.5 C23.5,14.1666667 23.5,13.5 23.5,13.5 C23.5,10.7385763 21.2614237,8.5 18.5,8.5 C15.7385763,8.5 13.5,10.7385763 13.5,13.5 C13.5,13.5 13.5,14.1666667 13.5,15.5" transform="rotate(90 18.5 12)" />
                </svg>
                <a href="#ParaqServe" rel="noopener noreferrer">Para que serve o Diadorim?</a>
            </li>
            <li>
                <svg width="24" height="24" viewBox="0 0 24 24" role="img" xmlns="http://www.w3.org/2000/svg" aria-labelledby="linkIconTitle" stroke="#000000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="none" color="#000000">
                    <title id="linkIconTitle">Link</title>
                    <path d="M10.5,15.5 C10.5,14.1666667 10.5,13.5 10.5,13.5 C10.5,10.7385763 8.26142375,8.5 5.5,8.5 C2.73857625,8.5 0.5,10.7385763 0.5,13.5 C0.5,13.5 0.5,14.1666667 0.5,15.5" transform="rotate(-90 5.5 12)" />
                    <path d="M8,12 L16,12" />
                    <path d="M23.5,15.5 C23.5,14.1666667 23.5,13.5 23.5,13.5 C23.5,10.7385763 21.2614237,8.5 18.5,8.5 C15.7385763,8.5 13.5,10.7385763 13.5,13.5 C13.5,13.5 13.5,14.1666667 13.5,15.5" transform="rotate(90 18.5 12)" />
                </svg>
                <a href="#autores" rel="noopener noreferrer">Para os Autores:</a>
            </li>
            <li>
                <svg width="24" height="24" viewBox="0 0 24 24" role="img" xmlns="http://www.w3.org/2000/svg" aria-labelledby="linkIconTitle" stroke="#000000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="none" color="#000000">
                    <title id="linkIconTitle">Link</title>
                    <path d="M10.5,15.5 C10.5,14.1666667 10.5,13.5 10.5,13.5 C10.5,10.7385763 8.26142375,8.5 5.5,8.5 C2.73857625,8.5 0.5,10.7385763 0.5,13.5 C0.5,13.5 0.5,14.1666667 0.5,15.5" transform="rotate(-90 5.5 12)" />
                    <path d="M8,12 L16,12" />
                    <path d="M23.5,15.5 C23.5,14.1666667 23.5,13.5 23.5,13.5 C23.5,10.7385763 21.2614237,8.5 18.5,8.5 C15.7385763,8.5 13.5,10.7385763 13.5,13.5 C13.5,13.5 13.5,14.1666667 13.5,15.5" transform="rotate(90 18.5 12)" />
                </svg>
                <a href="#editores" rel="noopener noreferrer">Para os Editores:</a>
            </li>
            <li>
                <svg width="24" height="24" viewBox="0 0 24 24" role="img" xmlns="http://www.w3.org/2000/svg" aria-labelledby="linkIconTitle" stroke="#000000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="none" color="#000000">
                    <title id="linkIconTitle">Link</title>
                    <path d="M10.5,15.5 C10.5,14.1666667 10.5,13.5 10.5,13.5 C10.5,10.7385763 8.26142375,8.5 5.5,8.5 C2.73857625,8.5 0.5,10.7385763 0.5,13.5 C0.5,13.5 0.5,14.1666667 0.5,15.5" transform="rotate(-90 5.5 12)" />
                    <path d="M8,12 L16,12" />
                    <path d="M23.5,15.5 C23.5,14.1666667 23.5,13.5 23.5,13.5 C23.5,10.7385763 21.2614237,8.5 18.5,8.5 C15.7385763,8.5 13.5,10.7385763 13.5,13.5 C13.5,13.5 13.5,14.1666667 13.5,15.5" transform="rotate(90 18.5 12)" />
                </svg>
                <a href="#gestores" rel="noopener noreferrer">Para os Gestores dos repositórios institucionais:</a>
            </li>
            <li>
                <svg width="24" height="24" viewBox="0 0 24 24" role="img" xmlns="http://www.w3.org/2000/svg" aria-labelledby="linkIconTitle" stroke="#000000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="none" color="#000000">
                    <title id="linkIconTitle">Link</title>
                    <path d="M10.5,15.5 C10.5,14.1666667 10.5,13.5 10.5,13.5 C10.5,10.7385763 8.26142375,8.5 5.5,8.5 C2.73857625,8.5 0.5,10.7385763 0.5,13.5 C0.5,13.5 0.5,14.1666667 0.5,15.5" transform="rotate(-90 5.5 12)" />
                    <path d="M8,12 L16,12" />
                    <path d="M23.5,15.5 C23.5,14.1666667 23.5,13.5 23.5,13.5 C23.5,10.7385763 21.2614237,8.5 18.5,8.5 C15.7385763,8.5 13.5,10.7385763 13.5,13.5 C13.5,13.5 13.5,14.1666667 13.5,15.5" transform="rotate(90 18.5 12)" />
                </svg>
                <a href="#importante" rel="noopener noreferrer">Por que é importante para o editor cadastrar a política editorial da revista no Diadorim?</a>
            </li>
            <li>
                <svg width="24" height="24" viewBox="0 0 24 24" role="img" xmlns="http://www.w3.org/2000/svg" aria-labelledby="linkIconTitle" stroke="#000000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="none" color="#000000">
                    <title id="linkIconTitle">Link</title>
                    <path d="M10.5,15.5 C10.5,14.1666667 10.5,13.5 10.5,13.5 C10.5,10.7385763 8.26142375,8.5 5.5,8.5 C2.73857625,8.5 0.5,10.7385763 0.5,13.5 C0.5,13.5 0.5,14.1666667 0.5,15.5" transform="rotate(-90 5.5 12)" />
                    <path d="M8,12 L16,12" />
                    <path d="M23.5,15.5 C23.5,14.1666667 23.5,13.5 23.5,13.5 C23.5,10.7385763 21.2614237,8.5 18.5,8.5 C15.7385763,8.5 13.5,10.7385763 13.5,13.5 C13.5,13.5 13.5,14.1666667 13.5,15.5" transform="rotate(90 18.5 12)" />
                </svg>
                <a href="#ComoFunciona" rel="noopener noreferrer">Como funciona o sistema de cores?</a>
            </li>
            <li>
                <svg width="24" height="24" viewBox="0 0 24 24" role="img" xmlns="http://www.w3.org/2000/svg" aria-labelledby="linkIconTitle" stroke="#000000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="none" color="#000000">
                    <title id="linkIconTitle">Link</title>
                    <path d="M10.5,15.5 C10.5,14.1666667 10.5,13.5 10.5,13.5 C10.5,10.7385763 8.26142375,8.5 5.5,8.5 C2.73857625,8.5 0.5,10.7385763 0.5,13.5 C0.5,13.5 0.5,14.1666667 0.5,15.5" transform="rotate(-90 5.5 12)" />
                    <path d="M8,12 L16,12" />
                    <path d="M23.5,15.5 C23.5,14.1666667 23.5,13.5 23.5,13.5 C23.5,10.7385763 21.2614237,8.5 18.5,8.5 C15.7385763,8.5 13.5,10.7385763 13.5,13.5 C13.5,13.5 13.5,14.1666667 13.5,15.5" transform="rotate(90 18.5 12)" />
                </svg>
                <a href="#qualDiferenca" rel="noopener noreferrer">Qual a diferença do pós-print do autor e do pós-print da revista?</a>
            </li>
            <li>
                <svg width="24" height="24" viewBox="0 0 24 24" role="img" xmlns="http://www.w3.org/2000/svg" aria-labelledby="linkIconTitle" stroke="#000000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="none" color="#000000">
                    <title id="linkIconTitle">Link</title>
                    <path d="M10.5,15.5 C10.5,14.1666667 10.5,13.5 10.5,13.5 C10.5,10.7385763 8.26142375,8.5 5.5,8.5 C2.73857625,8.5 0.5,10.7385763 0.5,13.5 C0.5,13.5 0.5,14.1666667 0.5,15.5" transform="rotate(-90 5.5 12)" />
                    <path d="M8,12 L16,12" />
                    <path d="M23.5,15.5 C23.5,14.1666667 23.5,13.5 23.5,13.5 C23.5,10.7385763 21.2614237,8.5 18.5,8.5 C15.7385763,8.5 13.5,10.7385763 13.5,13.5 C13.5,13.5 13.5,14.1666667 13.5,15.5" transform="rotate(90 18.5 12)" />
                </svg>
                <a href="#sistemaDeCores" rel="noopener noreferrer">Por que o Diadorim usa este sistema de cores para categorizar as políticas?</a>
            </li>
            <li>
                <svg width="24" height="24" viewBox="0 0 24 24" role="img" xmlns="http://www.w3.org/2000/svg" aria-labelledby="linkIconTitle" stroke="#000000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="none" color="#000000">
                    <title id="linkIconTitle">Link</title>
                    <path d="M10.5,15.5 C10.5,14.1666667 10.5,13.5 10.5,13.5 C10.5,10.7385763 8.26142375,8.5 5.5,8.5 C2.73857625,8.5 0.5,10.7385763 0.5,13.5 C0.5,13.5 0.5,14.1666667 0.5,15.5" transform="rotate(-90 5.5 12)" />
                    <path d="M8,12 L16,12" />
                    <path d="M23.5,15.5 C23.5,14.1666667 23.5,13.5 23.5,13.5 C23.5,10.7385763 21.2614237,8.5 18.5,8.5 C15.7385763,8.5 13.5,10.7385763 13.5,13.5 C13.5,13.5 13.5,14.1666667 13.5,15.5" transform="rotate(90 18.5 12)" />
                </svg>
                <a href="#cadastroRevista" rel="noopener noreferrer">Como cadastrar minha revista?</a>
            </li>
            <li>
                <svg width="24" height="24" viewBox="0 0 24 24" role="img" xmlns="http://www.w3.org/2000/svg" aria-labelledby="linkIconTitle" stroke="#000000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="none" color="#000000">
                    <title id="linkIconTitle">Link</title>
                    <path d="M10.5,15.5 C10.5,14.1666667 10.5,13.5 10.5,13.5 C10.5,10.7385763 8.26142375,8.5 5.5,8.5 C2.73857625,8.5 0.5,10.7385763 0.5,13.5 C0.5,13.5 0.5,14.1666667 0.5,15.5" transform="rotate(-90 5.5 12)" />
                    <path d="M8,12 L16,12" />
                    <path d="M23.5,15.5 C23.5,14.1666667 23.5,13.5 23.5,13.5 C23.5,10.7385763 21.2614237,8.5 18.5,8.5 C15.7385763,8.5 13.5,10.7385763 13.5,13.5 C13.5,13.5 13.5,14.1666667 13.5,15.5" transform="rotate(90 18.5 12)" />
                </svg>
                <a href="#revistaCadastrada" rel="noopener noreferrer">Qualquer revista pode ser cadastrada?</a>
            </li>
            <li>
                <svg width="24" height="24" viewBox="0 0 24 24" role="img" xmlns="http://www.w3.org/2000/svg" aria-labelledby="linkIconTitle" stroke="#000000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="none" color="#000000">
                    <title id="linkIconTitle">Link</title>
                    <path d="M10.5,15.5 C10.5,14.1666667 10.5,13.5 10.5,13.5 C10.5,10.7385763 8.26142375,8.5 5.5,8.5 C2.73857625,8.5 0.5,10.7385763 0.5,13.5 C0.5,13.5 0.5,14.1666667 0.5,15.5" transform="rotate(-90 5.5 12)" />
                    <path d="M8,12 L16,12" />
                    <path d="M23.5,15.5 C23.5,14.1666667 23.5,13.5 23.5,13.5 C23.5,10.7385763 21.2614237,8.5 18.5,8.5 C15.7385763,8.5 13.5,10.7385763 13.5,13.5 C13.5,13.5 13.5,14.1666667 13.5,15.5" transform="rotate(90 18.5 12)" />
                </svg>
                <a href="#comoAlterar" rel="noopener noreferrer">Como alterar as informações do registro?</a>
            </li>
        </ul>
    </div>
    <div class="container-about">
        
        <h2 id="OqDiadorim">O que é Diadorim?</h2>
        <p class="text-about">O Diretório de políticas editoriais das revistas científicas brasileiras (Diadorim) é um serviço do <a href="https://ibict.br/" target="_blank">Instituto Brasileiro de Informação em Ciência e Tecnologia (Ibict)</a> que reúne as políticas editoriais sobre o armazenamento e acesso aos artigos das revistas científicas brasileiras em repositórios institucionais de acesso aberto.</p>
        <h2 id="nameDiadorim"> Por que o nome Diadorim?</h2>
        <p class="text-about">Diadorim é um dos personagens do livro “Grande Sertão: Veredas”, um dos clássicos romances da literatura brasileira cujo autor é João Guimarães Rosa. O nome foi escolhido com vistas a acompanhar a tendência internacional de nomear diretórios e serviços de informação científica homenageando obras da literatura do país em que o sistema foi desenvolvido.</p>
        <h2 id="ParaqServe"> Para que serve o Diadorim?</h2>
        <p class="text-about">O Diadorim serve para localizar informações sobre as políticas de acesso e armazenamento dos artigos das revistas científicas brasileiras em repositórios institucionais de acesso aberto. É um serviço voltado para os autores, editores de revistas e para gestores de repositórios institucionais.</p>
        <h2 id="autores"> Para os autores:</h2>
        <p class="text-about">Serve para que os autores saibam se a revista em que pretendem publicar suas pesquisas permite o armazenamento e acesso de uma cópia de seu artigo em repositórios institucionais. Desta forma, os autores podem selecionar uma revista científica que atende suas necessidades.</p>
        <h2 id="editores"> Para os editores:</h2>
        <p class="text-about">Serve para que os editores informem ou estabeleçam a política editorial de suas revistas no que diz respeito ao acesso, armazenamento e condições de uso em repositórios institucionais de acesso aberto. Divulgando a política editorial, a possibilidade de cumprimento do acordo estabelecido entre autores e editores torna-se mais fácil, uma vez que se torna mais conhecido.</p>
        <h2 id="gestores">Para os gestores dos repositórios institucionais:</h2>
        <p class="text-about">Serve para que os gestores dos repositórios institucionais saibam se a instituição editora da revista que publicou determinado artigo permite que ele seja armazenado e acessado no repositórios, bem como as condições estabelecidas para tal.</p>
        <h2 id="importante"> Por que é importante para o editor cadastrar a política editorial da revista no Diadorim?</h2>
        <p class="text-about">Ao cadastrar a política editorial da revista os editores tornam mais visíveis a permissão e as condições para o armazenamento dos artigos em repositórios institucionais. Tornar estas informações mais visíveis auxilia no cumprimento do acordo estabelecido entre os autores e os editores.</p>
        <h2 id="ComoFunciona">Como funciona o sistema de cores?</h2>
        <p class="text-about">O sistema de cores funciona para categorizar as políticas editoriais segundo a permissão de armazenamento e acesso dos artigos em repositórios institucionais. Existem quatro categorias para as permissões, são elas:</p>
        <div class="container-cores">
        <div class="cores">
            <p id="icon-selo">
                <svg width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <rect width="48" height="48" rx="24" fill="#FFD400" />
                    <path d="M46.0354 30.0299C45.4232 34.32 43.431 45.0962 31.1867 43.2576C21.6246 41.8217 15.0835 42.3322 13.691 34.7014C12.6602 29.0534 10.5391 24.7251 8.10734 24.4318C-1.31986 23.2946 1.34368 12.2569 6.85349 7.35394C14.3582 0.675788 21.8848 7.62408 23.1093 11.3013C24.0888 14.2431 30.3043 11.8334 33.9776 11.2206C47.4463 10.6077 46.6476 25.7398 46.0354 30.0299Z" fill="#FFD400" />
                    <path fill-rule="evenodd" clip-rule="evenodd" d="M15 18C15.5523 18 16 18.4477 16 19V24H21C21.5523 24 22 24.4477 22 25C22 25.5523 21.5523 26 21 26H15C14.4477 26 14 25.5523 14 25V19C14 18.4477 14.4477 18 15 18Z" fill="#463A01" />
                    <path fill-rule="evenodd" clip-rule="evenodd" d="M23.999 19L24 19C26.6522 19 29.1957 20.0536 31.0711 21.9289C32.9464 23.8043 34 26.3478 34 29C34 29.5523 33.5523 30 33 30C32.4477 30 32 29.5523 32 29C32 26.8783 31.1571 24.8434 29.6569 23.3431C28.1567 21.843 26.122 21.0001 24.0005 21C22.0322 21.0021 20.1337 21.7298 18.6683 23.0439C18.6681 23.0441 18.6685 23.0437 18.6683 23.0439L15.669 25.7433C15.2585 26.1128 14.6262 26.0795 14.2567 25.669C13.8872 25.2585 13.9205 24.6262 14.331 24.2567L17.3323 21.5556C19.1644 19.9124 21.538 19.0025 23.999 19Z" fill="#463A01" />
                </svg>
            </p>
            <p class="text-about"><b>Amarela:</b> Permite o armazenamento e acesso das versões preprint dos documentos em repositórios institucionais/digitais</p>
        </div>
        <div class="cores">
            <p id="icon-selo">
                <svg width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <g clip-path="url(#clip0_98_7004)">
                        <rect width="48" height="48" rx="24" fill="#00D5FF" />
                        <path fill-rule="evenodd" clip-rule="evenodd" d="M33 18C33.5523 18 34 18.4478 34 19V25C34 25.5523 33.5523 26 33 26H27C26.4478 26 26 25.5523 26 25C26 24.4478 26.4478 24 27 24H32V19C32 18.4478 32.4478 18 33 18Z" fill="#E8FBFF" />
                        <path fill-rule="evenodd" clip-rule="evenodd" d="M23.9996 21C21.878 21.0002 19.8434 21.843 18.3432 23.3432C16.8429 24.8435 16 26.8783 16 29C16 29.5523 15.5523 30 15 30C14.4478 30 14 29.5523 14 29C14 26.3479 15.0536 23.8043 16.929 21.929C18.8043 20.0536 21.3479 19 24 19H24.0011C26.462 19.0026 28.8357 19.9124 30.6677 21.5556L30.669 21.5568L33.669 24.2568C34.0795 24.6262 34.1128 25.2585 33.7433 25.669C33.3739 26.0795 32.7416 26.1128 32.3311 25.7433L29.3324 23.0445C29.3321 23.0443 29.3319 23.0441 29.3317 23.0439C27.8663 21.7299 25.9678 21.0022 23.9996 21Z" fill="#E8FBFF" />
                    </g>
                    <defs>
                        <clipPath id="clip0_98_7004">
                            <rect width="48" height="48" rx="24" fill="white" />
                        </clipPath>
                    </defs>
                </svg>
            </p>
            <p class="text-about"> <b>Azul:</b> Permite o armazenamento e acesso das versões pós-print dos documentos em repositórios institucionais/digitais</p>
        </div>
        <div class="cores">
            <p id="icon-selo">
                <svg width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <rect width="48" height="48" rx="24" fill="#E9E9E9" />
                    <rect width="48" height="48" rx="24" fill="url(#paint0_linear_98_7002)" />
                    <path fill-rule="evenodd" clip-rule="evenodd" d="M27 15C27 14.4477 27.4477 14 28 14H33C33.5523 14 34 14.4477 34 15V20C34 20.5523 33.5523 21 33 21C32.4477 21 32 20.5523 32 20V16H28C27.4477 16 27 15.5523 27 15Z" fill="#363636" />
                    <path fill-rule="evenodd" clip-rule="evenodd" d="M33.7071 14.2929C34.0976 14.6834 34.0976 15.3166 33.7071 15.7071L16.7071 32.7071C16.3166 33.0976 15.6834 33.0976 15.2929 32.7071C14.9024 32.3166 14.9024 31.6834 15.2929 31.2929L32.2929 14.2929C32.6834 13.9024 33.3166 13.9024 33.7071 14.2929Z" fill="#363636" />
                    <path fill-rule="evenodd" clip-rule="evenodd" d="M33 27C33.5523 27 34 27.4477 34 28V33C34 33.5523 33.5523 34 33 34H28C27.4477 34 27 33.5523 27 33C27 32.4477 27.4477 32 28 32H32V28C32 27.4477 32.4477 27 33 27Z" fill="#363636" />
                    <path fill-rule="evenodd" clip-rule="evenodd" d="M26.2929 26.2929C26.6834 25.9024 27.3166 25.9024 27.7071 26.2929L33.7071 32.2929C34.0976 32.6834 34.0976 33.3166 33.7071 33.7071C33.3166 34.0976 32.6834 34.0976 32.2929 33.7071L26.2929 27.7071C25.9024 27.3166 25.9024 26.6834 26.2929 26.2929Z" fill="#363636" />
                    <path fill-rule="evenodd" clip-rule="evenodd" d="M15.2929 15.2929C15.6834 14.9024 16.3166 14.9024 16.7071 15.2929L21.7071 20.2929C22.0976 20.6834 22.0976 21.3166 21.7071 21.7071C21.3166 22.0976 20.6834 22.0976 20.2929 21.7071L15.2929 16.7071C14.9024 16.3166 14.9024 15.6834 15.2929 15.2929Z" fill="#363636" />
                    <defs>
                        <linearGradient id="paint0_linear_98_7002" x1="-2.66667" y1="-15.7333" x2="17.6" y2="24" gradientUnits="userSpaceOnUse">
                            <stop stop-color="#E1E0E0" />
                            <stop offset="1" stop-color="white" stop-opacity="0" />
                        </linearGradient>
                    </defs>
                </svg>
            </p>
            <p class="text-about">  <b>Branca: </b>Apresenta restrições para o armazenamento e acesso das versões preprint e pós-print dos documentos em repositórios institucionais/digitais</p>
        </div>
        <div class="cores">
            <p id="icon-selo">
                <svg width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <rect width="48" height="48" rx="24" fill="#00FF80" />
                    <path fill-rule="evenodd" clip-rule="evenodd" d="M28.2929 13.2929C28.6834 12.9024 29.3166 12.9024 29.7071 13.2929L33.7071 17.2929C34.0976 17.6834 34.0976 18.3166 33.7071 18.7071L29.7071 22.7071C29.3166 23.0976 28.6834 23.0976 28.2929 22.7071C27.9024 22.3166 27.9024 21.6834 28.2929 21.2929L31.5858 18L28.2929 14.7071C27.9024 14.3166 27.9024 13.6834 28.2929 13.2929Z" fill="#00552B" />
                    <path fill-rule="evenodd" clip-rule="evenodd" d="M19 19C18.2044 19 17.4413 19.3161 16.8787 19.8787C16.3161 20.4413 16 21.2044 16 22V23C16 23.5523 15.5523 24 15 24C14.4477 24 14 23.5523 14 23V22C14 20.6739 14.5268 19.4021 15.4645 18.4645C16.4021 17.5268 17.6739 17 19 17H33C33.5523 17 34 17.4477 34 18C34 18.5523 33.5523 19 33 19H19Z" fill="#00552B" />
                    <path fill-rule="evenodd" clip-rule="evenodd" d="M19.7071 25.2929C20.0976 25.6834 20.0976 26.3166 19.7071 26.7071L16.4142 30L19.7071 33.2929C20.0976 33.6834 20.0976 34.3166 19.7071 34.7071C19.3166 35.0976 18.6834 35.0976 18.2929 34.7071L14.2929 30.7071C13.9024 30.3166 13.9024 29.6834 14.2929 29.2929L18.2929 25.2929C18.6834 24.9024 19.3166 24.9024 19.7071 25.2929Z" fill="#00552B" />
                    <path fill-rule="evenodd" clip-rule="evenodd" d="M33 24C33.5523 24 34 24.4477 34 25V26C34 27.3261 33.4732 28.5979 32.5355 29.5355C31.5979 30.4732 30.3261 31 29 31H15C14.4477 31 14 30.5523 14 30C14 29.4477 14.4477 29 15 29H29C29.7956 29 30.5587 28.6839 31.1213 28.1213C31.6839 27.5587 32 26.7956 32 26V25C32 24.4477 32.4477 24 33 24Z" fill="#00552B" />
                </svg>
            </p>
            <p class="text-about"><b>Verde: </b>Permite o armazenamento e acesso das versões preprint e pós-print dos documentos em repositórios institucionais/digitais</p>
        </div>
        </div>
        <h2 id="qualDiferenca">Qual a diferença do pós-print do autor e do pós-print da revista?</h2>
        <p class="text-about">O pós-print do autor corresponde à versão do artigo avaliada pela revista e corrigida pelo autor, mas ainda não publicada pela revista. Já o pós-print da revista refere-se à versão do artigo já corrigida pelo autor e publicada pela revista.</p>
        <h2 id="sistemaDeCores">Por que o Diadorim usa este sistema de cores para categorizar as políticas?</h2>
        <p class="text-about">Porque este é o sistema mais utilizado internacionalmente para categorizar as políticas editoriais das revistas científicas. O sistema foi criado pelo Diretório Sherpa/Romeo, que é um serviço similar ao Diadorim, mas tem o foco na região europeia. Assim como o Diadorim e o Sherpa/Romeo, existem outros diretórios para as políticas editoriais das revistas científicas, por exemplo: Blimunda, em Portugal, e o Dulcinea, na Espanha.</p>
        <h2 id="cadastroRevista">Como cadastrar minha revista?</h2>
        <p class="text-about">O Diadorim funciona de maneira integrada a um outro serviço desenvolvido e mantido pelo <a href="https://ibict.br/" target="_blank" rel="noopener noreferrer"> Instituto Brasileiro de Informação em Ciência e Tecnologia (Ibict)</a>, o <a href="https://miguilim.ibict.br/" target="_blank" rel="noopener noreferrer">Diretório das revistas científicas eletrônicas brasileiras (Miguilim). </a>Desta forma, o cadastro de uma revista deve ser feito diretamente no Miguilim, e assim que o registro for aprovado ele aparecerá automaticamente nos dois serviços.
        </p>
        <h2 id="revistaCadastrada">Qualquer revista pode ser cadastrada?</h2>
        <p class="text-about">Somente as revistas científicas eletrônicas editadas e publicadas no Brasil podem ser cadastradas. Dentre as revistas científicas brasileiras, qualquer uma pode se cadastrar, independente da área de conhecimento. No entanto, todo cadastro é sujeito à aprovação.</p>
        <h2 id="comoAlterar">Como alterar as informações do registro?</h2>
        <p class="text-about">Para alterar alguma informação do registro da revista, deve ser feita atualização nos dados diretamente no Miguilim. Assim que aprovada, as alterações constarão em ambos os serviços. Em caso de dúvidas, utilize o botão “Contato” do Diadorim para falar com a equipe gestora.
        </p>
    </div>
    <div class="topo">
        <a href="#OqDiadorim" rel="noopener noreferrer" class="btn-topo">
            <svg fill="#ff7900" width="24" height="24" viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg">
                <path d="M 16 6.59375 L 15.28125 7.28125 L 2.78125 19.78125 L 4.21875 21.21875 L 16 9.4375 L 27.78125 21.21875 L 29.21875 19.78125 L 16.71875 7.28125 Z" />
            </svg>
        </a>
        <span class="text-about">Topo</span>
    </div>
</div>