<?php $this->headTitle($this->translate('Criterios')); ?>
<?php $this->layout()->searchbox = false; ?>

<div class="about">

    <h2> <strong class="criterios-titulo">Critérios básicos para cadastro</strong></h2>
    <p class="criterios-descricao">Para que uma revista seja aceita no Diadorim ela deverá cumprir os seguintes requisitos mínimos:</p>
    <ul class="criterios-lista">
        <li>Ter registro de ISSN para o suporte eletrônico;</li>
        <li>Ter o Brasil como país de publicação na rede ISSN;</li>
        <li>Ser eletrônica e estar disponível online;</li>
        <li>Manter conexão permanente e estável com a internet;</li>
        <li>Ser de caráter acadêmico-científico, levando em consideração os seguintes requisitos:</li>
        <ul>
            <li>Publicar artigos originais e que tenham sido previamente submetidos à revisão por pares;</li>
            <li>Ter corpo editorial composto por pesquisadores especialistas na área de atuação da revista.</li>
        </ul>

    </ul>

</div>