<!-- Imagem de background adicionada separadamente -->
<div class="home_background" />

<div class="row home_row">
  <div class="col col-md-7 home_col">
    <h1 class="home_title">
      Diadorim
    </h1>

    <p class="home-long-text">
      <span>é um serviço de informações relativas às </span>
      <span>autorizações concedidas para o armazenamento </span>
      <span>e o acesso dos artigos das revistas brasileiras </span>
      <span>em repositórios digitais de acesso aberto.</span>
    </p>

    <div class="home_cards"></div>
  </div>

  <div class="col col-md-5">

  </div>
</div>