<!-- Imagem de background adicionada separadamente -->
<div class="home_background" />

<div class="row home_row">
  <div class="col col-md-7 home_col">
    <h1 class="home_title">
      <span class="span1"> Diadorim </span> <br>
      <!-- <span class="span2">é um serviço</span> -->
    </h1>

    <span class="home_long-text">
      é um serviço de informações relativas às <br>
      autorizações concedidas para o armazenamento <br>
      e o acesso dos artigos das revistas brasileiras <br>
      em repositórios digitais de acesso aberto.
    </span>

    <div class="home_cards"></div>
  </div>

  <div class="col col-md-5">

  </div>
</div>