<!-- Imagem de background adicionada separadamente -->
<div class="home_background" />

<div class="row home_row">
  <div class="col col-md-7 home_col">
    <h1 class="home_title">
      Diadorim
    </h1>

    <p class="home-long-text">
      <span>é um serviço de informações relativas às </span>
      <span>autorizações concedidas para o armazenamento </span>
      <span>e o acesso dos artigos das revistas brasileiras </span>
      <span>em repositórios digitais de acesso aberto.</span>
    </p>

    <div class="home_cards"></div>

    <div class="col col-md-5">

    </div>
    <div class="searchHomeContent selos">
      <div class="definicao-icons">
        <img src="/diadorim/themes/diadorim/images/i-iconss/svg/selo-branca.svg" alt="">
        <p>Apresenta restrições para o armazenamento e acesso das versões preprint e pós-print dos documentos em repositórios institucionais/digitais</p>
      </div>
      </div>
      <div class="searchHomeContent selos">
      <div class="definicao-icons">
      <img src="/diadorim/themes/diadorim/images/icons/svg/selo-azul.svg" alt="">
        <p>Apresenta restrições para o armazenamento e acesso das versões preprint e pós-print dos documentos em repositórios institucionais/digitais</p>
      </div>
      </div>
      <div class="searchHomeContent selos">
      <div class="definicao-icons">
      <img src="/diadorim/themes/diadorim/images/icons/svg/selo-amarela.svg" alt="">
        <p>Apresenta restrições para o armazenamento e acesso das versões preprint e pós-print dos documentos em repositórios institucionais/digitais</p>
      </div>
      </div>
      <div class="searchHomeContent selos">
      <div class="definicao-icons">
        <img src="/diadorim/themes/diadorim/images/icons/svg/selo-verde.svg" alt="">
        <p>Apresenta restrições para o armazenamento e acesso das versões preprint e pós-print dos documentos em repositórios institucionais/digitais</p>
      </div>
      </div>
   
  </div>

</div>