<?php
$this->headScript()->appendFile('facets.js');

// Save results/options to $this so they are available to sub-templates:
$this->results = $results = $this->recommend->getResults();
$this->options = $options = $results->getOptions();
$collapsedFacets = $this->recommend->getCollapsedFacets();
$forceUncollapsedFacets = [];

// Make sure facets with active selections are not collapsed:
$filterList = $results->getParams()->getFilterList(true);
foreach ($filterList as $field => $filters) {
  foreach ($filters as $filter) {
    $index = isset($filter['field']) ? array_search($filter['field'], $collapsedFacets) : false;
    if ($index !== false) {
      unset($collapsedFacets[$index]); // Open if we have a match
      $forceUncollapsedFacets[] = $filter['field'];
    }
  }
}

$hierarchicalFacets = $this->recommend->getHierarchicalFacets();
if ($hierarchicalFacets) {
  // jstree.min.js used to be injected by hierarchical-facet.js, but with deferred
  // processing it's called too late to append anything to the headers.
  $this->headScript()->appendFile('vendor/jsTree/jstree.min.js');
  $this->headScript()->appendFile('jstree-vufind-facet-plugin.js');
}
?>
<button class="close-offcanvas btn btn-link" data-toggle="offcanvas"><?= $this->transEsc('navigate_back') ?></button>
<?php
$checkboxFilters = $this->recommend->getCheckboxFacetSet();
$hasVisibleCheckboxes = false;
if (count($checkboxFilters) > 0) {
  foreach ($checkboxFilters as $current) {
    if ($results->getResultTotal() > 0 || $current['alwaysVisible']) {
      $hasVisibleCheckboxes = true;
      break;
    }
  }
}
?>
<?php if ($results->getResultTotal() > 0 || $hasVisibleCheckboxes) : ?>
  <!-- <h2><?= $this->transEsc($this->slot('side-facet-caption')->get('Refine Results')) ?></h2> -->
  <span class="sr-only"><?= $this->transEscAttr('page_reload_on_select_hint') ?></span>
<?php endif; ?>
<?php if ($hasVisibleCheckboxes) : ?>
  <div class="checkboxFilter">
    <?= $this->context($this)->renderInContext('Recommend/SideFacets/checkbox-filters.phtml', ['checkboxFilters' => $checkboxFilters, 'results' => $results]); ?>
  </div>
<?php endif; ?>
<?= $this->sideFacetExtraControls ?? '' ?>
<?php $sideFacetSet = $this->recommend->getFacetSet(); ?>
<?php $hierarchicalFacets = $this->recommend->getHierarchicalFacets() ?>
<?php $hierarchicalFacetSortOptions = $this->recommend->getHierarchicalFacetSortOptions() ?>
<?php if (!empty($sideFacetSet) && $results->getResultTotal() > 0) : ?>
  <?php foreach ($sideFacetSet as $title => $cluster) : ?>
    <?php $collapsed = in_array($title, $collapsedFacets); ?>
    <?php // Data-title attribute is for analytics use.  Do not remove.
    ?>

    <!-- substitui os pontos do nome do campo, por traços. Com os pontos no nome, da erro no controle do javascript na hora de fazer o 'toglge' -->
    <?php $titleWithHyphen = str_replace(".", "--", $title); ?>

    <div class="facet-group" id="side-panel-<?= $this->escapeHtmlAttr($titleWithHyphen) ?>" data-title="<?= $this->escapeHtmlAttr($cluster['label']) ?>">
      <button class="title<?php if ($collapsed) : ?> collapsed<?php endif ?>" data-toggle="collapse" data-target="#side-collapse-<?= $this->escapeHtmlAttr($titleWithHyphen) ?>">
        <span class="facet-title"><?= $this->transEsc($cluster['label']) ?></span>
        <!-- Removendo o antigo icone do accordion -->
        <!-- <?= $this->icon('collapse', 'facet-title-icon') ?> -->

        <span class="show--open">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16" fill="none">
            <path fill-rule="evenodd" clip-rule="evenodd" d="M3.52876 5.52858C3.78911 5.26823 4.21122 5.26823 4.47157 5.52858L8.00016 9.05717L11.5288 5.52858C11.7891 5.26823 12.2112 5.26823 12.4716 5.52858C12.7319 5.78892 12.7319 6.21103 12.4716 6.47138L8.47157 10.4714C8.21122 10.7317 7.78911 10.7317 7.52876 10.4714L3.52876 6.47138C3.26841 6.21103 3.26841 5.78892 3.52876 5.52858Z" fill="#071D41" />
          </svg>
        </span>
        <span class="show--closed">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-up">
            <polyline points="18 15 12 9 6 15"></polyline>
          </svg>
        </span>
      </button>

      <div id="side-collapse-<?= $this->escapeHtmlAttr($titleWithHyphen) ?>" role="listbox" aria-expanded="<?= $collapsed ? 'false' : 'true' ?>" class="collapse<?php if (!$collapsed) : ?> in<?php endif ?>" <?php if (in_array($title, $forceUncollapsedFacets)) : ?> data-force-in="1" <?php endif ?>>
        <?=
        $this->context($this)->renderInContext(
          'Recommend/SideFacets/facet.phtml',
          [
            'facet' => $title,
            'cluster' => $cluster,
            'collapsedFacets' => $collapsedFacets,
          ]
        );
        ?>
      </div>
    </div>
  <?php endforeach; ?>
<?php endif; ?>
<?= $this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, "registerSideFacetTruncation();", 'SET'); ?>