<?php
echo $this->headScript()->appendFile("loadFields.js");
echo $this->headScript()->appendFile('/lib/jspdf.umd.min.js');

?>

<?php
$formatter = $this->recordDataFormatter($this->driver);
$coreFields = $formatter->getData($formatter->getDefaults($this->defaults ?? 'core'));
$config = $this->config()->get('config');
$handleBaseUrl = $config->Miguilim->handleBaseUrl ?? 'https://miguilim.ibict.br/handle/';
?>

<!-- Adicionado essa nova forma de renderizar os spans para conseguir realiazar duas 
verificaões em labels diferentes sem quebrar o layout -->
<?php foreach ($coreFields as $current) : ?>
  <?php
  $label = $this->transEsc($current['label']);
  $lowercaseLabel = strtolower($label);
  $value = $current['value'];
  ?>

  <?php if ($lowercaseLabel === 'título' || $lowercaseLabel === 'title') : ?>
    <?php
    $title = $value;
    $this->headTitle($title);
    ?>
  <?php endif; ?>

  <?php if ($lowercaseLabel === 'selo de armazenamento e acesso' || $lowercaseLabel === 'Seal Color') : ?>
    <?php
    $sealColor = strtolower(explode(":", $value)[0]);
    ?>
  <?php endif; ?>

  <?php if ($lowercaseLabel === 'handle' || $lowercaseLabel === 'identificador') : ?>
    <?php
    $handleLink = '<a target="blank" href="' . $handleBaseUrl . $value . '">' . $handleBaseUrl  . $value . '</a>';
    ?>
  <?php endif; ?>
<?php endforeach; ?>

<div class="record-card">
  <?php if (!empty($coreFields)) : ?>
    <div class="record-card_header">
      <div class="record-header">
        <div>
          <span class="title">
            <?= $this->transEsc('Title') ?>:
          </span>
          <h1>
            <?= $title ?>
          </h1>
        </div>
        <div>
          <?php if (isset($sealColor)) : ?>
            <?php if (strlen($sealColor) < 20) : ?>
              <img alt="selo <?= $sealColor ?>" src="<?= $this->imageLink('./icons/svg/selo-' . $sealColor . '.svg'); ?>" width="40.976px" height="40.976px">
            <?php else : ?>
              <span class="blank-seal-color" title="<?= $sealColor ?>"></span>
            <?php endif; ?>
          <?php endif; ?>
        </div>
      </div>
      <span>
        Para ver mais informações do item acesse: <?= $handleLink ?>
      </span>

      <!-- <button id="pdfButton"  onclick="gerarPDF()" class="btn-pdf">Imprimir em PDF</button> -->

      <div class="record-card_body">
        <table <?php if (!empty($this->tableId)) : ?>id="<?= $this->tableId ?>" <?php endif; ?>class="table table-striped">
          <caption class="sr-only"><?= $this->transEsc($this->caption ?? 'Bibliographic Details') ?></caption>

          <?php foreach ($coreFields as $current) : ?>
            <tr>
              <th><?= $this->transEsc($current['label']) ?>: </th>
              <td><?= $current['value'] ?></td>
            </tr>
          <?php endforeach; ?>
        </table>
      </div>
    <?php endif; ?>
    </div>