<?php
$this->metadata()->generateMetatags($this->driver);
?>
<div class="media" vocab="http://schema.org/" resource="#record" typeof="<?= $this->driver->getSchemaOrgFormats() ?> Product">
  <?php
  $QRCode = $this->record($this->driver)->getQRCode("core");
  $coverDetails = $this->record($this->driver)->getCoverDetails('core', 'medium', $this->record($this->driver)->getThumbnail('large'));
  $cover = $coverDetails['html'];
  $preview = ($this->previewOverride ?? false)
    ? $this->previewOverride : $this->record($this->driver)->getPreviews();
  $rating = $this->driver->isRatingAllowed();
  ?>

  <div class="media-body">

    <h1 property="name"><?= $this->escapeHtml($this->driver->getShortTitle() . ' ' . $this->driver->getSubtitle() . ' ' . $this->driver->getTitleSection()) ?></h1>
    <?php foreach ($this->driver->tryMethod('getFullTitlesAltScript', [], []) as $altTitle) : ?>
      <div class="title-alt">
        <?= $this->escapeHtml($altTitle) ?>
      </div>
    <?php endforeach; ?>

    <?php if (!empty($this->extraControls)) : ?>
      <?= $this->extraControls['actionControls'] ?? '' ?>
      <?= $this->extraControls['availabilityInfo'] ?? '' ?>
    <?php endif; ?>

    <?php if ($this->searchOptions($this->driver->getSourceIdentifier())->getVersionsAction()) : ?>
      <?= $this->record($this->driver)->renderTemplate('versions-link.phtml') ?>
    <?php endif; ?>

    <?php $summary = $this->driver->getSummary();
    $summary = isset($summary[0]) ? $this->escapeHtml($summary[0]) : false; ?>
    <?php if ($summary) : ?>
      <p><?= $this->truncate($summary, 300) ?></p>

      <?php if (strlen($summary) > 300) : ?>
        <p><a href="<?= $this->escapeHtmlAttr($this->recordLinker()->getTabUrl($this->driver, 'Description')) ?>#tabnav"><?= $this->transEsc('Full description') ?></a></p>
      <?php endif; ?>
    <?php endif; ?>

    <?php if ($this->userlist()->getMode() !== 'disabled') : ?>
      <?php /* Display the lists that this record is saved to */ ?>
      <div class="savedLists">
        <strong><?= $this->transEsc("Saved in") ?>:</strong>
      </div>
    <?php endif; ?>

    <?php /* Display Main Details */ ?>
    <?=
    $this->record($this->driver)->renderTemplate(
      'core-fields.phtml',
      [
        'driver' => $this->driver,
        'defaults' => 'core',
      ]
    );
    ?>
    <?php /* End Main Details */ ?>
  </div>
</div>