<?php
$formatter = $this->recordDataFormatter($this->driver);
$coreFields = $formatter->getData($formatter->getDefaults($this->defaults ?? 'core'));
?>

<!-- Adicionado essa nova forma de renderizar os spans para conseguir realiazar duas 
verificaões em labels diferentes sem quebrar o layout -->
<?php foreach ($coreFields as $current) : ?>
  <?php
  $label = $this->transEsc($current['label']);
  $lowercaseLabel = strtolower($label);
  $value = $current['value'];
  ?>

  <?php if ($lowercaseLabel === 'título' || $lowercaseLabel === 'title') : ?>
    <?php
    $labelSpan = '<span>' . $label . ':</span>';
    $valueSpan = '<span>' . $value . '</span>';
    ?>
  <?php endif; ?>

  <?php if ($lowercaseLabel === 'handle') : ?>
    <?php
    $description = 'Use este identificador para citar ou linkar para este item:';
    $handleLink = '<a href="https://miguilim.ibict.br/handle/' . $value . '">https://miguilim.ibict.br/handle/' . $value . '</a>';
    $handleText = '<span>' . $description . ' ' . $handleLink . '</span>';
    ?>
  <?php endif; ?>
<?php endforeach; ?>

<div class="record-card">
  <?php if (!empty($coreFields)) : ?>
    <div class="record-card_header">
      <?= $labelSpan ?>
      <?= $valueSpan ?>

      <?= $handleText ?>
    </div>

    <div class="record-card_body">
      <table <?php if (!empty($this->tableId)) : ?>id="<?= $this->tableId ?>" <?php endif; ?>class="table table-striped">
        <caption class="sr-only"><?= $this->transEsc($this->caption ?? 'Bibliographic Details') ?></caption>

        <?php foreach ($coreFields as $current) : ?>
          <tr>
            <th><?= $this->transEsc($current['label']) ?>: </th>
            <td><?= $current['value'] ?></td>
          </tr>
        <?php endforeach; ?>
      </table>
    </div>
  <?php endif; ?>
</div>