<?php
$account = $this->auth()->getManager();
?>


<nav class="banner navbar navbar-defaul">
  <div class="container-fluid">
    <div class="container">
      <?php if (!isset($this->layout()->renderingError)) : ?>
        <div class="nav-all">
          <div>
            <div class="nav navbar-nav image">
              <a class="logo-ibict text-center" href="https://ibict.br" target="_blank">
                <img src="<?= $this->imageLink('logo-ibict.png'); ?>" alt="Logo IBICT" width="103.13" height="45.33">
              </a>

              <a class="logo-diadorim text-center" href="<?= $this->url('home') ?>">
                <img src="<?= $this->imageLink('logo-diadorim.png'); ?>" alt="Logo IBICT" width="113" height="44">
              </a>
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#header-collapse" aria-hidden="true">
                <?= $this->icon('ui-menu') ?>
              </button>
            </div>
          </div>
          <div class="collapse navbar-collapse" id="header-collapse">
            <ul class=" nav navbar-nav text">
              <li>
                <a id="initialPage" href="<?= $this->url('home') ?>" class="text-decoration-none text-center">
                  <span class="icon icon--font fa fa-home" role="img" aria-hidden="true"></span>
                  <span><?= $this->transEsc('Home') ?></span>
                </a>
              </li>
              <li><a id="navigate" href="<?= $this->url('search-results') ?>" class="text-decoration-none text-center"><?= $this->transEsc("Navigate") ?></a></li>
              <li><a id="about" href="<?= $this->url('sobre-home') ?>" class="text-decoration-none text-center"><?= $this->transEsc("Sobre") ?></a></li>
              <li><a id="logosSection" href="<?= $this->url('logomarcas-home') ?>" class="text-decoration-none text-center"><?= $this->transEsc("Logomarcas") ?></a></li>
              <li>
                <a id="feedbackLink" class="text-decoration-none text-center" data-lightbox href="<?= $this->url('feedback-home') ?>">
                  <?= $this->transEsc("Contact") ?>
                </a>
              </li>
            </ul>
          </div>
        </div>
      <?php endif; ?>
    </div>
  </div>
</nav>