<?php $account = $this->auth()->getManager(); ?>

<nav class="banner navbar navbar-defaul">
  <div class="container-fluid">
    <!-- Essa div ficará visível apenas no mobile -->
    <div class="row">
      <div class="navbar-header">
        <button
          type="button"
          class="navbar-toggle collapsed"
          data-toggle="collapse"
          data-target="#header-collapse"
          aria-hidden="true"
          
        >
          <?= $this->icon('ui-menu') ?>
        </button>

        <!-- <a class="navbar-brand lang-<?= $this->layout()->userLang ?>" href="<?= $this->url('home') ?>">
          <img
            src="../images/logo-gov-br.png"
            alt="Logo gov.br"
            width="62"
            height="40"
          >
        </a> -->

        <!-- <a class="navbar-brand" href="<?= $this->url('home') ?>">
          <img
            src="../images/logo-gov-br.png"
            alt="Logo gov.br"
            width="62"
            height="40"
          >
        </a> -->
      </div>
    </div>
  
    <div class="row">
      <?php if (!isset($this->layout()->renderingError)) : ?>  
        <div class="collapse navbar-collapse text-center" id="header-collapse">
          <ul class="nav navbar-nav">
            <li>
              <a class="logo-ibict text-center" href="<?= $this->url('home') ?>">
                <img
                  src="<?= $this->imageLink('logo-ibict.png'); ?>"
                  alt="Logo IBICT"
                  width="103.13"
                  height="45.33"
                >
              </a>
            </li>

            <li>
              <a class="logo-diadorim text-center" href="<?= $this->url('home') ?>">
                <img
                  src="<?= $this->imageLink('logo-diadorim.png'); ?>"
                  alt="Logo IBICT"
                  width="113"
                  height="44"
                >
              </a>
            </li>
          </ul>

          <ul class="nav navbar-nav">
            <li>
              <a class="text-decoration-none text-center active-link">
                <img
                  src="<?= $this->imageLink('home.png'); ?>"
                  alt="Logo Home"
                  width="24"
                  height="24"
                >
                <span>Página Inicial</span>
              </a>
            </li>
            <li><a class="text-decoration-none text-center">Navegar</a></li>
            <li><a class="text-decoration-none text-center">Sobre</a></li>
            <li><a class="text-decoration-none text-center">Cadastro</a></li>
            <li><a class="text-decoration-none text-center">Contato</a></li>
          </ul>
          
          <ul class="nav navbar-nav navbar-right">
            <!-- <?php if ($this->feedback()->tabEnabled()) : ?>
              <li>
                <a class="icon-link" id="feedbackLink" data-lightbox href="<?= $this->url('feedback-home') ?>">
                  <?= $this->icon('feedback', 'icon-link__icon') ?>
                  <span class="icon-link__label"><?= $this->transEsc("Feedback") ?></span>
                </a>
              </li>
            <?php endif; ?> -->
            <!-- <?php $cart = $this->cart();
            if ($cart->isActive()) : ?>
              <li id="cartSummary">
                <a id="cartItems" class="icon-link" data-lightbox title="<?= $this->transEscAttr('View Book Bag') ?>" href="<?= $this->url('cart-home') ?>">
                  <?= $this->icon('cart', 'icon-link__icon') ?>
                  <span class="icon-link__label">
                    <span class="sr-only"><?= $this->transEsc('Book Bag') ?>:</span>
                    <span role="status"><strong><?= count($cart->getItems()) ?></strong> <?= $this->transEsc('items') ?></span>
                    <span class="full<?= !$cart->isFull() ? ' hidden' : '' ?>">(<?= $this->transEsc('bookbag_full') ?>)</span>
                  </span>
                </a>
              </li>
            <?php endif; ?> -->
            <?php if (is_object($account) && $account->loginEnabled()) : // hide login/logout if unavailable
            ?>
              <?php if ($account->isLoggedIn()) : ?>
                <li class="logoutOptions<?php if ($account->dropdownEnabled()) : ?> with-dropdown<?php endif ?>">
                  <a href="<?= $this->url('myresearch-home', [], ['query' => ['redirect' => 0]]) ?>" class="icon-link">
                    <span id="account-icon" class="icon-link__icon"><?= $this->icon('my-account') ?></span>
                    <span class="icon-link__label"><?= $this->transEsc("Your Account") ?></span>
                  </a>
                </li>
                <?php if ($account->dropdownEnabled()) : ?>
                  <li id="login-dropdown" class="dropdown">
                    <a href="#" data-toggle="dropdown"><?= $this->icon('dropdown-caret') ?></a>
                    <div class="dropdown-menu">
                      <?= $this->render('myresearch/menu'); ?>
                    </div>
                  </li>
                <?php endif; ?>
                <li class="logoutOptions">
                  <a href="<?= $this->url('myresearch-logout') ?>" class="logout icon-link">
                    <?= $this->icon('sign-out', 'icon-link__icon') ?>
                    <span class="icon-link__label"><?= $this->transEsc("Log Out") ?></span>
                  </a>
                </li>

              <?php else : ?>
                <li id="loginOptions">
                  <?php if ($account->getSessionInitiator($this->serverUrl($this->url('myresearch-home')))) : ?>
                    <a href="<?= $this->url('myresearch-userlogin') ?>" class="icon-link">
                      <?= $this->icon('sign-in', 'icon-link__icon') ?>
                      <span class="icon-link__label"><?= $this->transEsc("Institutional Login") ?></span>
                    </a>
                  <?php else : ?>
                    <!-- <a href="<?= $this->url('myresearch-userlogin') ?>" class="icon-link text-center" data-lightbox>
                      <?= $this->icon('sign-in', 'icon-link__icon') ?>
                      <img src="<?= $this->imageLink('user-circle'); ?>" alt="Login"><?= $this->transEsc("Login") ?></span>
                    </a> -->

                    <!-- Removido o ícone natural do login -->
                    <a href="<?= $this->url('myresearch-userlogin') ?>" class="icon-link text-center" data-lightbox>
                      
                      <img
                        src="<?= $this->imageLink('user-circle.png'); ?>"
                        alt="Login"
                        width="24"
                        height="24"
                      >
                      <span> <?= $this->transEsc("Login") ?> </span>
                    </a>
                  <?php endif; ?>
                </li>
              <?php endif; ?>
            <?php endif; ?>

            <?php if (isset($this->layout()->themeOptions) && count($this->layout()->themeOptions) > 1) : ?>
              <?= $this->component('menu-button', [
                'toggleLabel' => 'Theme',
                'wrapperTag' => 'li',
                'menuItems' => array_map(
                    function ($item) {
                    $item['label'] = $item['desc'];
                    $item['url'] = $this->url()->addQueryParameters(['ui' => $item['name']]);

                    return $item;
                  },
                    $this->layout()->themeOptions
                ),
              ]) ?>
            <?php endif; ?>
            
            <!-- Dropdown de idiomas comentado, pois não há no novo layout -->
            <!-- <?php if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1) : ?>
              <?= $this->component('menu-button', [
                'toggleLabel' => 'Language',
                'wrapperClass' => 'language',
                'wrapperTag' => 'li',
                'menuItems' => array_map(
                    function ($langCode, $langName) {
                    return [
                      'label' => $this->displayLanguageOption($langName),
                      'url' => $this->url()->addQueryParameters(['lng' => $langCode]),
                      'selected' => $this->layout()->userLang == $langCode,
                    ];
                  },
                    array_keys($this->layout()->allLangs),
                    array_values($this->layout()->allLangs),
                ),
              ]) ?>
            <?php endif; ?> -->
          </ul>
        </div>
      <?php endif; ?>
    </div>
  </div>
</nav>

<?php if ($this->layout()->searchbox !== false) : ?>
  <div class="search container navbar">
    <div class="nav searchbox hidden-print" role="search">
      <?= $this->layout()->searchbox ?>
    </div>
  </div>
<?php endif; ?>