<?php $account = $this->auth()->getManager(); ?>

<nav class="banner navbar navbar-defaul">
  <div class="container-fluid">
    <!-- Essa div ficará visível apenas no mobile -->
    <div class="row">
      <div class="navbar-header">
        <button
          type="button"
          class="navbar-toggle collapsed"
          data-toggle="collapse"
          data-target="#header-collapse"
          aria-hidden="true"
          
        >
          <?= $this->icon('ui-menu') ?>
        </button>

        <!-- <a class="navbar-brand lang-<?= $this->layout()->userLang ?>" href="<?= $this->url('home') ?>">
          <img
            src="../images/logo-gov-br.png"
            alt="Logo gov.br"
            width="62"
            height="40"
          >
        </a> -->

        <!-- <a class="navbar-brand" href="<?= $this->url('home') ?>">
          <img
            src="../images/logo-gov-br.png"
            alt="Logo gov.br"
            width="62"
            height="40"
          >
        </a> -->
      </div>
    </div>
  
    <div class="row">
      <?php if (!isset($this->layout()->renderingError)) : ?>  
        <div class="collapse navbar-collapse text-center" id="header-collapse">
          <ul class="nav navbar-nav">
            <li>
              <a class="logo-ibict text-center" href="<?= $this->url('home') ?>">
                <img
                  src="<?= $this->imageLink('logo-ibict.png'); ?>"
                  alt="Logo IBICT"
                  width="103.13"
                  height="45.33"
                >
              </a>
            </li>

            <li>
              <a class="logo-diadorim text-center" href="<?= $this->url('home') ?>">
                <img
                  src="<?= $this->imageLink('logo-diadorim.png'); ?>"
                  alt="Logo IBICT"
                  width="113"
                  height="44"
                >
              </a>
            </li>
          </ul>

          <ul class="nav navbar-nav">
            <li>
              <a class="text-decoration-none text-center active-link">
                <img
                  src="<?= $this->imageLink('home.png'); ?>"
                  alt="Logo Home"
                  width="24"
                  height="24"
                >
                <span>Página Inicial</span>
              </a>
            </li>
            <li><a class="text-decoration-none text-center">Navegar</a></li>
            <li><a class="text-decoration-none text-center">Sobre</a></li>
            <li><a class="text-decoration-none text-center">Cadastro</a></li>
            <li><a class="text-decoration-none text-center">Contato</a></li>
            <li id="loginOptions">
              <?php if ($account->getSessionInitiator($this->serverUrl($this->url('myresearch-home')))) : ?>
                <a href="<?= $this->url('myresearch-userlogin') ?>" class="icon-link">
                  <?= $this->icon('sign-in', 'icon-link__icon') ?>
                  <span class="icon-link__label"><?= $this->transEsc("Institutional Login") ?></span>
                </a>
              <?php else : ?>
                <!-- <a href="<?= $this->url('myresearch-userlogin') ?>" class="icon-link text-center" data-lightbox>
                  <?= $this->icon('sign-in', 'icon-link__icon') ?>
                  <img src="<?= $this->imageLink('user-circle'); ?>" alt="Login"><?= $this->transEsc("Login") ?></span>
                </a> -->

                <!-- Removido o ícone natural do login -->
                <a href="<?= $this->url('myresearch-userlogin') ?>" class="icon-link text-center" data-lightbox>
                  
                  <img
                    src="<?= $this->imageLink('user-circle.png'); ?>"
                    alt="Login"
                    width="24"
                    height="24"
                  >
                  <span> <?= $this->transEsc("Login") ?> </span>
                </a>
              <?php endif; ?>
            </li>
          </ul>
        </div>
      <?php endif; ?>
    </div>
  </div>
</nav>

<?php if ($this->layout()->searchbox !== false) : ?>
  <div class="search container navbar">
    <div class="nav searchbox hidden-print" role="search">
      <?= $this->layout()->searchbox ?>
    </div>
  </div>
<?php endif; ?>