<?php
// Set a default page title; this will usually be overridden when a tab is
// loaded, but it may be useful if there are no tabs, or when tabs are loaded
// via AJAX:
$this->headTitle($this->driver->getBreadcrumb());

// Set up standard record scripts:
$this->headScript()->appendFile("record.js");
$this->headScript()->appendFile("check_save_statuses.js");
// Activate Syndetics Plus if necessary:
if ($this->syndeticsPlus()->isActive()) {
  $this->headScript()->appendFile($this->syndeticsPlus()->getScript());
}
// Add any extra scripts the tabs require:
foreach ($this->tabsExtraScripts as $script) {
  $this->headScript()->appendFile($script);
}

// Add RDF header link if applicable:
if ($this->export()->recordSupportsFormat($this->driver, 'RDF')) {
  $this->headLink()->appendAlternate($this->recordLinker()->getActionUrl($this->driver, 'RDF'), 'application/rdf+xml', 'RDF Representation');
}

// Set up breadcrumbs:
$this->layout()->breadcrumbs = $this->searchMemory()->getLastSearchLink($this->transEsc('Search'), '<li>', '</li> ') .
  '<li class="active" aria-current="page">' . $this->recordLinker()->getBreadcrumbHtml($this->driver) . '</li> ';
$this->layout()->title = $this->driver->getShortTitle();
?>

<?php if (isset($this->scrollData) && ($this->scrollData['previousRecord'] || $this->scrollData['nextRecord'])) : ?>
  <?= $this->render('record/prev-next.phtml'); ?>
<?php endif; ?>

<?= $this->record($this->driver)->getToolbar() ?>


<div class="main-container record source<?= $this->escapeHtmlAttr($this->driver->getSourceIdentifier()) ?>">
  <?php $sidebarList = $this->related()->getList($this->driver); ?>
  <div>
    <input type="hidden" value="<?= $this->escapeHtmlAttr($this->driver->getUniqueId()) ?>" class="hiddenId">
    <input type="hidden" value="<?= $this->escapeHtmlAttr($this->driver->getSourceIdentifier()) ?>" class="hiddenSource">
    <?= $this->flashmessages() ?>
    <?= $this->record($this->driver)->getCoreMetadata() ?>

    <?= $this->driver->supportsCoinsOpenURL() ? '<span class="Z3988" title="' . $this->escapeHtmlAttr($this->driver->getCoinsOpenURL()) . '"></span>' : '' ?>
  </div>

  <!-- <div class="<?= $this->layoutClass('sidebar') ?>">
    <?php foreach ($sidebarList as $current) : ?>
      <?= $this->related()->render($current) ?>
    <?php endforeach; ?>
  </div> -->
</div>
<?= $this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, '$(document).ready(recordDocReady);', 'SET'); ?>