<?php $this->headTitle($this->translate('Logomarcas')); ?>
<?php $this->layout()->searchbox = false; ?>


<!-- <?php echo $this->headScript()->appendFile("/diadorim/themes/diadorim/js/loadFields.js"); ?> -->

<div class="logosSection">
    <section id="selo-section">
        <div class="searchHomeContent selos principal">
            <div class="logo-content">
                <h3 class="title-logo"> Logotipo oficial do Diadorim pode ser utilizado por todas as revistas devidamente cadastradas no Diretório</h3>
                <div>
                    <img class="logo-image" src="../themes/diadorim/images/icons/svg/DIADORIM_COMPLETO.svg" alt="definição do selo oficinal">
                </div>
                <a href="../themes/diadorim/images/icons/svg/DIADORIM_COMPLETO.svg" download title="kedna">
                    <img class="download-icon" src="../themes/diadorim/images/icons/svg/cloud-arrow.svg" alt="definição do selo oficinal">
                </a>
            </div>

        </div>
        <div class="searchHomeContent selos secundario">
            <h5 class="title-logo">A critério de cada revista, pode também ser utilizado o logotipo em que consta o selo que foi atribuído à revista no Diretório</h5>

            <div class="definicao-icons">
                <img class="logo-image" src="../themes/diadorim/images/icons/svg/DIADORIM_BRANCO.svg" alt="selo branco do diadorim">
                <p class="logo-description">Branco: Apresenta restrições para o armazenamento e acesso das versões preprint e pós-print dos documentos em repositórios institucionais/digitais</p>

            </div>
            <a href="../themes/diadorim/images/icons/svg/DIADORIM_BRANCO.svg" download>
                <img class="download-icon" src="../themes/diadorim/images/icons/svg/cloud-arrow.svg" alt="selo l">
            </a>
            
            <div class="definicao-icons">
                <img class="logo-image" src="../themes/diadorim/images/icons/svg/DIADORIM_AZUL.svg" alt="selo azul do diadorim">
                <p class="logo-description">Azul: Permite o armazenamento e acesso das versões pós-print dos documentos em repositórios institucionais/digitais</p>
            </div>
            <a href="../themes/diadorim/images/icons/svg/DIADORIM_AZUL.svg" download>
                <img class="download-icon" src="../themes/diadorim/images/icons/svg/cloud-arrow.svg" alt="definição do selo oficinal">
            </a>

            <div class="definicao-icons">
                <img class="logo-image " src="../themes/diadorim/images/icons/svg/DIADORIM_AMARELO.svg" alt="selo amarelo do diadorim">

                <p class="logo-description">Amarelo: Permite o armazenamento e acesso das versões preprint dos documentos em repositórios institucionais/digitais</p>

            </div>
            <a href="../themes/diadorim/images/icons/svg/DIADORIM_AMARELO.svg" download>
                <img class="download-icon" src="../themes/diadorim/images/icons/svg/cloud-arrow.svg" alt="definição do selo oficinal">
            </a>

            <div class="definicao-icons">
                <img class="logo-image" src="../themes/diadorim/images/icons/svg/DIADORIM_VERDE.svg" alt="selo verde do diadorim">
                <p class="logo-description">Verde: Permite o armazenamento e acesso das versões preprint e pós-print dos documentos em repositórios institucionais/digitais</p>
            </div>
            <a href="../themes/diadorim/images/icons/svg/DIADORIM_VERDE.svg" download>
                <img class="download-icon" src="../themes/diadorim/images/icons/svg/cloud-arrow.svg" alt="definição do selo oficinal">
            </a>
        </div>
    </section>
</div>
<!-- <div class="modal-logo">
            <button class="btn-logo" data-dismiss="modal" >Cancelar</button>
            <button class="btn-logo"id="download-btn" >Download</button>
        </div> -->

</div>