<?php $this->headTitle($this->translate('Logomarcas')); ?>
<?php $this->layout()->searchbox = false; ?>


<?php echo $this->headScript()->appendFile("loadFields.js"); ?>

<div class="logosSection">
    <section id="selo-section">
        <div class="searchHomeContent selos principal">
            <div class="logo-content">
                <div class="description ">
                    <img class="logo-image" id="selo1" src="../themes/diadorim/images/icons/svg/DIADORIM_COMPLETO.svg" alt="definição do selo oficinal">
                    <h3 class="title-logo"> Logotipo oficial do Diadorim pode ser utilizado por todas as revistas devidamente cadastradas no Diretório</h3>
                    <a href="../themes/diadorim/images/icons/svg/DIADORIM_COMPLETO.svg" download title="Dowload do selo" class="download-icon" id="download-link" >
                        <img class="rotate-icon" src="../themes/diadorim/images/icons/svg/arrow-right-to-bracket-solid (1).svg" alt="definição do selo oficinal">
                    </a>
                </div>
            </div>

        </div>
        <div class="searchHomeContent selos secundario">
            <h4 class="title-logo">A critério de cada revista, pode também ser utilizado o logotipo em que consta o selo que foi atribuído à revista no Diretório</h4>

            <div class="description ">
                <img class="logo-image" src="../themes/diadorim/images/icons/svg/DIADORIM_BRANCO.svg" alt="selo branco do diadorim">
                <p class="logo-description">Branco: Apresenta restrições para o armazenamento e acesso das versões preprint e pós-print dos documentos em repositórios institucionais/digitais</p>
                <a href="../themes/diadorim/images/icons/svg/DIADORIM_BRANCO.svg" download title="Dowload do selo branco"  class="download-icon">
                    <img class="rotate-icon" src="../themes/diadorim/images/icons/svg/arrow-right-to-bracket-solid (1).svg" alt="selo ">
                </a>

            </div>

            <div class="description ">
                <img class="logo-image" src="../themes/diadorim/images/icons/svg/DIADORIM_AZUL.svg" alt="selo azul do diadorim">
                <p class="logo-description">Azul: Permite o armazenamento e acesso das versões pós-print dos documentos em repositórios institucionais/digitais</p>
                <a href="../themes/diadorim/images/icons/svg/DIADORIM_AZUL.svg" download title="Dowload do selo azul" class="download-icon">
                    <img class="rotate-icon" src="../themes/diadorim/images/icons/svg/arrow-right-to-bracket-solid (1).svg" alt="definição do selo oficinal"  >
                </a>
            </div>

            <div class="description ">
                <img class="logo-image " src="../themes/diadorim/images/icons/svg/DIADORIM_AMARELO.svg" alt="selo amarelo do diadorim">

                <p class="logo-description">Amarelo: Permite o armazenamento e acesso das versões preprint dos documentos em repositórios institucionais/digitais</p>
                <a href="../themes/diadorim/images/icons/svg/DIADORIM_AMARELO.svg" download title="Dowload do selo amarelo"  class="download-icon">
                    <img class="rotate-icon" src="../themes/diadorim/images/icons/svg/arrow-right-to-bracket-solid (1).svg" alt="definição do selo oficinal" >
                </a>

            </div>

            <div class="description ">
                <img class="logo-image" src="../themes/diadorim/images/icons/svg/DIADORIM_VERDE.svg" alt="selo verde do diadorim">
                <p class="logo-description">Verde: Permite o armazenamento e acesso das versões preprint e pós-print dos documentos em repositórios institucionais/digitais</p>
                <a href="../themes/diadorim/images/icons/svg/DIADORIM_VERDE.svg" download title="Dowload do selo verde"  class="download-icon">
                    <img class="rotate-icon" src="../themes/diadorim/images/icons/svg/arrow-right-to-bracket-solid (1).svg" alt="definição do selo oficinal">
                </a>
            </div>

        </div>
    </section>
    <div class="modal-logo">
        <button class="btn-logo" id="cancel-btn">Cancelar</button>
        <button class="btn-logo" id="download-btn" title="Download de todas as logos">Download</button>
    </div>

</div>
</div>